<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:tns="http://www.totvs.com/"
    targetNamespace="http://www.totvs.com/"
    name="IwsDataServer">

    <wsdl:types>
        <xs:schema
            elementFormDefault="qualified"
            targetNamespace="http://www.totvs.com/">

            <xs:element name="ReadRecord">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="DataServerName" type="xs:string" minOccurs="0"/>
                        <xs:element name="PrimaryKey" type="xs:string" minOccurs="0"/>
                        <xs:element name="Contexto" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="ReadRecordResponse">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="ReadRecordResult" type="xs:string" minOccurs="0"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

        </xs:schema>
    </wsdl:types>

    <wsdl:message name="ReadRecordSoapIn">
        <wsdl:part name="parameters" element="tns:ReadRecord"/>
    </wsdl:message>

    <wsdl:message name="ReadRecordSoapOut">
        <wsdl:part name="parameters" element="tns:ReadRecordResponse"/>
    </wsdl:message>

    <wsdl:portType name="IwsDataServer">
        <wsdl:operation name="ReadRecord">
            <wsdl:input message="tns:ReadRecordSoapIn"/>
            <wsdl:output message="tns:ReadRecordSoapOut"/>
        </wsdl:operation>
    </wsdl:portType>

    <wsdl:binding name="BasicHttpBinding_IwsDataServer" type="tns:IwsDataServer">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>

        <wsdl:operation name="ReadRecord">
            <soap:operation
                soapAction="http://www.totvs.com/IwsDataServer/ReadRecord"
                style="document"/>

            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>

            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="wsDataServer">
        <wsdl:port name="BasicHttpBinding_IwsDataServer" binding="tns:BasicHttpBinding_IwsDataServer">
            <soap:address location="http://sgehomolog.fiepi.com.br:8051/wsDataServer/IwsDataServer"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>
